### ISSUE TITLE
Graphic Bug of "Progress Bar"

### ISSUE THREAD

**Issue by chgad** [mimischi/django-clock#347]
I recently experienced, that even if i have no shifts in a month already, the Progressbar shows Progress. No numbers though but the bar isnt empty. See the picture
![grafik](https://cloud.githubusercontent.com/assets/21121667/26776973/bc996360-49db-11e7-9895-aee3041decc6.png)

**Comment by mimischi** [comment]
It's actually a feature. I defined a specific width for empty or almost empty progress bars, so that you're always able to read the text. The reasoning comes from the [Bootstrap 3 documentation](http://getbootstrap.com/components/#progress).

Assume the following cases:

- 0% Progress: do not have a blue bar, and set the text font to black.
- 5% Progress: we have a small blue bar, but the text will overflow to the right of the bar.

In the current implementation, we overcome the whole "text does not fit into the progress bar neatly"-problem, by just defining some default width that all bars have.



Maybe we _could_  resolve the problem by using [Input groups](http://getbootstrap.com/components/#input-groups), but I'm not sure if that would make for a better UI/UX.

**Comment by mimischi** [comment]
It's a feature™️.
