### ISSUE TITLE
Should we get rid of shift pausing?

### ISSUE THREAD

**Issue by mimischi** [mimischi/django-clock#446]
## Introduction

The new time sheet layout proposes to cumulate every shift from a specific day and display it as a continuous shift. While display is not necessarily a problem, we have to think how we adopt this inside the backend.

Currently every `Shift` object holds, among other information, the following data:
```
shift_started: Start of the shift (Datetime)
shift_finished: End of the shift (Datetime)
pause_duration: Duration of the shifts pause (Timedelta)
```

## Status quo

In our current implementation of the system a user can start a shift, pause it and finish it. The  total work time is a simple calculation of `(shift_finished - shift_started) - pause_duration`. This way users can start a shift, pause it during lunch and resume it after that.
The export at the end of the month will print out every shift in its own row, producing several shifts per day, if the user has clocked in several shifts on the same day.

## Question

Do users actually expect to have the ability to pause a shift? Let's take a moment and look at the possibilities.

### 1. Remove pausing of shifts completely

In this approach, a user may only start and stop a shift. If the user goes for a lunch break, they will stop the shift and then start a new one, as soon as they are back at work.

If a user adds several shifts to one day, we will automatically calculate a `pause_duration` during the export of shifts. In this case the `pause_duration` will be calculated by the difference of `shift1_finished` and `shift2_started`. Therefore the whole work duration will be: `(shift2_finished - shift1_started) - (shift2_started - shift1_finished)`.

When a user adds a shift manually that is already completed, the user would have to actually create two separate shift objects, if they have done a pause and want to document it. This may be bad UX.

### 2. Keep pauses, but only allow editing for manual entries

Here we would remove the "Pause"-Button when using the Clock-in/clock-out Buttons, letting the user only start and stop a shift. When they want to edit a shift or add others, that they have already completed, then they would be able to also specify pause durations.

Similar to the previous point, if a user has two individual shifts on the same day, the time between the two shifts would also add up to a "pause" in the total working time of the day.

### 3. Keep pausing system as is

In this case we would not touch pauses and keep them like they are currently. Users can clock-in, pause and clock-out of shifts, as well as manually edit/add shifts and specify pause times.

## Research

So far, the Clock production site has almost 1200 finished shifts. I will export and analyze these, to get a grasp, whether the current user base actually uses the pause functionality.

### Preparation

Command used to export the shift data:
```bash
python manage.py dumpdata shifts --indent 4 --exclude auth --exclude contenttypes >  $(date +"%Y%m%d")_clock_dump.json
```
Converted JSON to CSV using [this online tool](https://konklone.io/json/).

**Comment by chgad** [comment]
The latest form of documenting shifts (see [Formularcenter](https://www.uni-frankfurt.de/47065133/formularcenter) ) has the flaw that what ever i do like e.g. working an hour, do something else 8 hours (study or have fun anythng) and again work 4 hours. What will i enter into the formular ? Ofc, i worked 5 hours straigth because an 8 hour pause isn't quite what i did. 

So consider the following steps before exporting the actual shifts of the month:

1. Allow more than 1 shift per day ( as it allready is)
2. delete the shift.pause option
3. before exporting accumulate all shift durations form all shifts per day .

**Comment by mimischi** [comment]
We actually asked the creator of the current time sheet of what his reasoning was.

Currently you have to input your gross (Brutto-Arbeitszeit) and net (Netto-Arbeitszeit) work times, for example:

1. Clock-in at 08:00 and work until 12:00 (4 hour work time)
2. Go to class from 12:00 until 16:00 (4 hour "pause:)
3. Work again from 16:00 until 20:00 (4 hour work time)

At the end of the day, you put in your start time at 08:00 and your end time at 20:00. Your gross work time is 12:00 hours, with a 4 hour pause: 8 hour work time. While it's not a pause as you would expect in a normal work day, it seems to work that way.

Why I like this idea is: it's simple. Your exported time sheet always has one page. If you export each shift separately (like Clock does currently), you risk the chance of producing a second (or even third) page. I'd go with paper conservation!

@chgad Do you think the following case is bad UX?
A user works from 08:00 until 16:00 and has a lunch break (lets say 30 minutes). If we remove the "pause" function and the user wants to specify the pause, then they need to add two separate shifts for that day with a gap in between.

At least I would think it's a hassle to specify two separate shifts, instead of one with a "pause field".

**Comment by mimischi** [comment]
Here is some simple analysis: https://github.com/mimischi/notebooks/blob/master/Clock%2Banalysis.ipynb

Nothing really interesting to see. Out of almost 1200 individual shifts, we have only 67 using pauses. Further only 16 people have actually used pauses (myself including). Only 7 (without myself) have used pauses more than twice.

**Comment by sheepyhollow** [comment]
Well - I basically agree with chgad. As long as we do not have external conditions requiring explicitly labelled pauses, we might as well get rid of them and just stick to shifts (and, implicitly, non-shifts).

If we state gross & net  in accordance with the actual HR sheet, the effective pauses are obscured anyway since we have cumulative active (work) and inactive (non-work) periods. What is given as pausing time value in the end is determined by the first and last shift's times - these boundaries are more or less arbitrary or at least meaningless (unless insurance issues are to be considered).

A 4 hour lecture-break is somehow counterintuitive - two shifts are far more comprehensible. And shift-working librarians can relate to the concept as well if... (see idea below).

As for the representation in the software, I'd suggest to keep the shift concept (without pausing) for the user view. The conversion to cumulative times is done during export. As long as the user can understand what the machine does (I want fancy animations with collapsing time bars! :smile:), clock can do whatever we like.

Depending on legal aspects and the answers of Mr. Scharf we might even think of labelling inactive times automatically as pauses (following some sophisticated concept). 
I could imagine the following:

- Students clock (start and stop) their work hours; there is no pause-Button
- Students edit shifts as they ever did 
- Students can manually designate pause times (for review on shiftlist/dashboard)
- upon export, the math is done - by now according to the requirement of the HR sheet

**Comment by sheepyhollow** [comment]
Perhaps we finde another way in accordance with legally required framing conditions.
Do we (does the HR department/the employer) need to now start & endtimes?

**Comment by mimischi** [comment]
>  Do we (does the HR department/the employer) need to now start & endtimes?

You're asking whether we actually can get rid of the exact start times of a shift and just output the gross/net duration for each day during export?

**Comment by sheepyhollow** [comment]
Ah... that's what I meant, basically. But I am not sure if this is already solved by our last discussion with HR.

**Comment by mimischi** [comment]
I need to check my notes from the last meeting, as I'm also not sure currently. I remember that we can get rid of some columns without any problems.
